#!/bin/sh

xrdb -I$HOME ~/.Xresources
compton --backend glx &
~/.fehbg
lemonbuddy_wrapper bar &
redshift &
dunst &
sxhkd &

bspc config border_width 4
bspc config focus_follows_pointer true
bspc config initial_polarity second_child
bspc config top_padding 24
bspc config window_gap 4

bspc monitor -d 1 2 3 4 5 6 7 8 9 0
