#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

source ~/.xprofile

xrdb -I$HOME ~/.Xresources
compton --backend glx &
~/.fehbg
redshift &
dunst &

export BSPWM_SOCKET=`mktemp -u --tmpdir bspwm-XXXXXXXXXX`
exec bspwm
