[dotrix.link]
"scripts/editor.sh" = "editor.sh"
"scripts/lock-screen.sh" = "lock-screen.sh"
"scripts/logout-menu.sh" = "logout-menu.sh"
"scripts/quit-i3.sh" = "quit-i3.sh"
"scripts/visual.sh" = "visual.sh"
