[alacritty.files]
"alacritty/alacritty.toml" = "~/.config/alacritty/alacritty.toml"

[dunst.files]
"dunst/dunstrc" = "~/.config/dunst/dunstrc"

[fish.files]
"fish/config.fish" = "~/.config/fish/config.fish"
"fish/fish_plugins" = "~/.config/fish/fish_plugins"

[git.files]
"git/gitconfig" = "~/.gitconfig"
"git/gitignore" = "~/.gitignore"
"git/gitattributes" = "~/.gitattributes"

[helix.files]
"helix/config.toml" = "~/.config/helix/config.toml"
"helix/languages.toml" = "~/.config/helix/languages.toml"

[niri]
depends = ["dunst", "waybar"]

[niri.files]
"niri/config.kdl" = "~/.config/niri/config.kdl"

[tinty.files]
"tinted-theming/tinty/config.toml" = "~/.config/tinted-theming/tinty/config.toml"

[waybar.files]
"waybar/config.jsonc" = "~/.config/waybar/config.jsonc"
"waybar/style.css" = "~/.config/waybar/style.css"
