#!/bin/zsh

export SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/gnupg/S.gpg-agent.ssh

if [[ $TERM == xterm ]]; then
    export TERM=xterm-256color
fi

export EDITOR=vim
export BROWSER=firefox
export PAGER=less

# export VGL_FPS=60
# export VGL_SPOIL=0
# export PRIMUS_SYNC=1
export RANGER_LOAD_DEFAULT_RC=FALSE
export _JAVA_AWT_WM_NONREPARENTING=1

# Prevent wine from creating stuff everywhere
export WINEDLLOVERRIDES=winemenubuilder.exe=d

# Use GTK style for QT5
export QT_STYLE_OVERRIDE=GTK+

# Rust
export PATH="$HOME/.cargo/bin:$PATH"
export RUST_SRC_PATH=~/code/rust/src
export CARGO_HOME=~/.cargo

# asp
export ASPROOT=~/packages/asp
