#!/bin/zsh

export SSH_AUTH_SOCK=~/.gnupg/S.gpg-agent.ssh

if [[ $TERM == xterm ]]; then
    export TERM=xterm-256color
fi

export EDITOR=~/scripts/editor.sh
export VISUAL=~/scripts/visual.sh
export BROWSER=/usr/bin/firefox
export PAGER=less
export LESS=FRX

export VGL_FPS=60
export VGL_SPOIL=0
export PRIMUS_SYNC=1
export RANGER_LOAD_DEFAULT_RC=FALSE

# Prevent wine from creating stuff everywhere
export WINEDLLOVERRIDES=winemenubuilder.exe=d

# Use GTK style for QT5
export QT_STYLE_OVERRIDE=GTK+
