#!/bin/zsh

# Install zgen if necessary
if [ ! -d ~/.zgen ]; then
    echo "Installing zgen"
    git clone https://github.com/tarjoilija/zgen.git ~/.zgen
fi

# Load zgen
source ~/.zgen/zgen.zsh

# Check if there's no init script
if ! zgen saved; then
    echo "Creating a zgen save"

    zgen oh-my-zsh lib/key-bindings.zsh
    zgen oh-my-zsh lib/history.zsh
    zgen oh-my-zsh lib/theme-and-appearance.zsh
    zgen oh-my-zsh lib/git.zsh
    zgen load zsh-users/zsh-completions src
    zgen load zsh-users/zsh-syntax-highlighting
    zgen load zsh-users/zsh-history-substring-search

    # Theme
    zgen load caiogondim/bullet-train-oh-my-zsh-theme bullet-train

    # Save init script
    zgen save
fi

# bullet-train colors
export BULLETTRAIN_TIME_SHOW=false
export BULLETTRAIN_GIT_EXTENDED=false
export BULLETTRAIN_STATUS_FG=22
export BULLETTRAIN_DIR_FG=26
export BULLETTRAIN_DIR_BG=25
export BULLETTRAIN_GIT_FG=26
export BULLETTRAIN_GIT_BG=24

# dircolors
eval $(dircolors)

# bind C-k and C-j for history browsing
bindkey '^K' history-substring-search-up
bindkey '^J' history-substring-search-down

# Completions
zstyle ':completion:*' menu select

# Aliases
alias e=$EDITOR
alias ls="ls -h --color=auto"
alias l=ls
alias ll="ls -l"
alias la="ls -a"
alias lla="ls -la"
alias pac=pacaur
alias cmus="tmux a -t cmus 2>/dev/null || tmux new -s cmus cmus"
