[dotrix.link]
".weechat/alias.conf" = "alias.conf"
".weechat/aspell.conf" = "aspell.conf"
".weechat/buffers.conf" = "buffers.conf"
".weechat/charset.conf" = "charset.conf"
".weechat/exec.conf" = "exec.conf"
".weechat/irc.conf" = "irc.conf"
".weechat/iset.conf" = "iset.conf"
".weechat/logger.conf" = "logger.conf"
".weechat/plugins.conf" = "plugins.conf"
".weechat/relay.conf" = "relay.conf"
".weechat/rmodifier.conf" = "rmodifier.conf"
".weechat/script.conf" = "script.conf"
".weechat/sec.conf" = "sec.conf"
".weechat/trigger.conf" = "trigger.conf"
".weechat/weechat.conf" = "weechat.conf"
".weechat/xfer.conf" = "xfer.conf"
